version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-test_k8s}
      POSTGRES_USER: ${POSTGRES_USER-test_k8s}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}

  web:
    image: iterekhov/django_app:1
    volumes:
      - ./backend_main_django:/code
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - db

volumes:
  db_data:
