apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: clearsession
            image: iterekhov/django_app:1
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py",  "clearsessions"]
            envFrom:
              - configMapRef:
                  name: django-configmap
        restartPolicy: OnFailure