apiVersion: batch/v1
kind: Job
metadata:
  name: migrates
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: migrate-job
        image: iterekhov/django_app:1
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py",  "migrate", "--no-input"]
        envFrom:
          - configMapRef:
              name: django-configmap
    restartPolicy: Never